name: Update News

on:
  schedule:
    - cron: "0 * * * *"   # Saatte 1
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          pip install feedparser requests beautifulsoup4 deep-translator

      - name: Generate news
        run: |
          python news/generator.py
          python scripts/build_latest.py

      - name: Commit & Push
        run: |
          git config user.name "news-bot"
          git config user.email "bot@users.noreply.github.com"
          git add news/latest.json
          git commit -m "update news" || echo "No changes"
          git push
